# Site settings
title: Gian Rothfuchs
name: Gian Marco Rothfuchs

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/GianRothfuchs
 - title: LinkedIn
   url: https://www.linkedin.com/in/gianrothfuchs
 - title: StackOverflow
   url: https://stackexchange.com/users/18643492/giro


#List of interesting Github repo/projects to include - optional
github:
 - gianrothfuchs/appliedRLBook
 - gianrothfuchs/rlSandbox
 - gianrothfuchs/RL_QLearning_ttt
 - gianrothfuchs/blockchain

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - Matlab
 - VBA
 - HTTP
 - REST
 - SQL
 - Finance
 - ESG
 - Statistics
 - Machine Learning
 - Deep Learning
 - Reinforcement Learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Portfolio Manager & PMS-Engineer
   start: 2018
   end: Ongoing
   employer: Swiss Rock Asset Management
   description: Portfolio Manager and Portfolio Management System Engineer
 - title: Quantitative Analyst
   start: 2015
   end: 2018
   employer: Credit Suisse AG
   description: Quantitative model developer in IRRBB Modelling
 - title: Research Assistant
   start: 2014
   end: 2015
   employer: Swiss National Bank
   description: Internship at International Trade and Capital Flows unit

#Education is required
education:
 - level: "M.A. in Economics"
   date: 2014
   subject: "Econometrics, Economic History, and Finance"
   school: University of Zurich
 - level: "B.A. in Economics"
   date: 2012
   subject: "Econometrics, Economic History, and Finance"
   school: University of Zurich

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/c2c9d6db2b95a351b6fe8e7f25477f26
   courses:
    - title: Deep Learning
      #link: https://www.coursera.org/specializations/deep-learning
      link: https://www.coursera.org/account/accomplishments/specialization/M3J9ND42TJ45
      optionalimage: https://github.com/GianRothfuchs/GianRothfuchs.github.io/raw/master/img/CourseraDL.png
      date: December 2017
    - title: Blockchain Specialization
      link: https://www.coursera.org/account/accomplishments/specialization/7STYEV4C7USB
      optionalimage: https://github.com/GianRothfuchs/GianRothfuchs.github.io/raw/master/img/CourseraBC.png
      date: August 2020
    - title: Data Streaming Nanodegree
      link: https://confirm.udacity.com/2PFPJKKX
      optionalimage: https://github.com/GianRothfuchs/GianRothfuchs.github.io/raw/master/img/UdacityDSN.png
      date: March 2021


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackexchange.com/users/18643492/giro
   flairimageurl: https://i.stack.imgur.com/Vn4Ql.png?s=128&g=1

intro: |
  I am a quantitative model developer with a strong focus on Finance. Personlly I am fascinated by the advances that have been made in the recent years by Deep Learning models. Guided by my personal interests I compiled a collection of Deep Learning models into this
  portfolio. The long term goal of this portfolio is to build a sense of how Deep Learning models may be transferred to applications in Financial research
  as well as practical questions in Finance.<br/><br/>
  Reinforcement Learning is one of my favourite applications of Deep Learning. A famous text book example ist the cart pole problem, where the learner (i.e. the model) observes the evironment consisting of a cart that balances as pole. The learner applies force ranging form -1 to 1 in order to prvent the pole from falling over for 200 consecutive periods. The full implementation can be found in my projects below. The animation below shows the trained model sucessfully solving the cart pole task after 50'000 training episodes.<br/><br/>
  <img src="https://raw.githubusercontent.com/GianRothfuchs/appliedRLBook/master/videos/chapter2/cartpole/vid.gif" alt="Learner balances pole for 200 steps (=Max)" / width="300" height="200">


 
#While most of the Deep Learning models are highly specific to a certain application, they also become increasingly popular in other fields.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Development Control</strong>: I have knowledge of application life-cycle management and have worked with SVN, Sourcetree, Git, and Jira.<br/><br/>
