# Site settings
title: Gian M. Rothfuchs
#twitter_username: rob_hinds
name: Gian Marco Rothfuchs

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/GianRothfuchs
 - title: LinkedIn
   url: www.linkedin.com/in/gianrothfuchs
 - title: StackOverflow
   url: https://stackexchange.com/users/18643492/giro

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - Matlab
 - VBA
 - HTTP
 - REST
 - SQL
 - Deep Learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Technical Project Support
   start: December 2018
   end: Ongoing
   employer: Swiss Rock Asset Management
   description: Portfolio management system implementation.
 - title: Quantitative Analyst
   start: June 2015
   end: November 2018
   employer: Credit Suisse AG
   description: Quantitative model developer in IRRBB Modelling.
 - title: Research Assistant
   start: June 2014
   end: June 2015
   employer: Swiss National Bank
   description: Internship at International Trade and Capital Flows unit.

#Education is required
education:
 - level: M.A. in Economics
   date: 2014
   subject: Econometrics, Economic History, and Finance
   school: University of Zurich
 - level: B.A. in Economics
   date: 2012
   subject: Econometrics, Economic History, and Finance
   school: University of Zurich

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization
      link: https://www.coursera.org/account/accomplishments/records/7N79KBED569A?utm_source=link&utm_medium=certificate&utm_content=cert_image&utm_campaign=sharing_cta&utm_product=course
      optionalimage: https://www.coursera.org/account/accomplishments/verify/7N79KBED569A?utm_source=link&utm_medium=certificate&utm_content=cert_image&utm_campaign=pdf_header_button&utm_product=course
      date: December 25, 2017
#    - title: Algorithms Design a
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: 
#      date: 

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018


#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
 - robhinds/opinionated-akka-http


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackexchange.com/users/18643492/giro
   flairimageurl: https://stackoverflow.com/users/flair/18643492.png

intro: |
  This Portfolio contains some of my data science projects.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>