# Site settings
title: Gian Rothfuchs
name: Gian Marco Rothfuchs

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/GianRothfuchs
 - title: LinkedIn
   url: https://www.linkedin.com/in/gianrothfuchs
 - title: StackOverflow
   url: https://stackexchange.com/users/18643492/giro


#List of interesting Github repo/projects to include - optional
github:
 - gianrothfuchs/appliedRLBook
 - gianrothfuchs/rlSandbox
 - gianrothfuchs/RL_QLearning_ttt

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - Matlab
 - VBA
 - HTTP
 - REST
 - SQL
 - Finance
 - Statistics
 - Machine Learning
 - Deep Learning
 - Reinforcement Learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Technical Project Support
   start: 2018
   end: Ongoing
   employer: Swiss Rock Asset Management
   description: Portfolio management system implementation
 - title: Quantitative Analyst
   start: 2015
   end: 2018
   employer: Credit Suisse AG
   description: Quantitative model developer in IRRBB Modelling
 - title: Research Assistant
   start: 2014
   end: 2015
   employer: Swiss National Bank
   description: Internship at International Trade and Capital Flows unit

#Education is required
education:
 - level: "M.A. in Economics"
   date: 2014
   subject: "Econometrics, Economic History, and Finance"
   school: University of Zurich
 - level: "B.A. in Economics"
   date: 2012
   subject: "Econometrics, Economic History, and Finance"
   school: University of Zurich

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/c2c9d6db2b95a351b6fe8e7f25477f26
   courses:
    - title: Deep Learning
      #link: https://www.coursera.org/specializations/deep-learning
      link: https://www.coursera.org/account/accomplishments/specialization/M3J9ND42TJ45
      optionalimage: http://coursera-university-assets.s3.amazonaws.com/2b/054650300011e9adc895106b89a651/GreyLogoName360x360.png
      date: December 2017
    - title: Blockchain Specialization
      link: https://www.coursera.org/account/accomplishments/records/T78E6CK2CSCG
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/20/53f890590611e8ad3a4787a17be710/New-blockchain-logo.jpg?auto=format%2Ccompress&dpr=2&w=85&h=85&fit=fill&bg=FFF
      date: Ongoing


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackexchange.com/users/18643492/giro
   flairimageurl: https://i.stack.imgur.com/Vn4Ql.png?s=128&g=1

intro: |
  I am a quantitative model developer with a strong focus on Finance. In my professional life there is a strong requirement for models
  that are simple and tractable. Therefore I have a clear tendency to choose models from ''classical econometrics'' domain for professional purposes. Personally
  I am fascinated by the advances that have been made by Deep Learning models. Following my interests I compiled a collection of Deep Learning models into this
  portfolio. The long term goal of this portfolio is to build a sense of how Deep Learning models may be transferred to applications in Financial research
  as well as practical questions in Finance.

 
#While most of the Deep Learning models are highly specific to a certain application, they also become increasingly popular in other fields.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Development Control</strong>: I have knowledge of application life-cycle management and have worked with SVN, Sourcetree, Git, and Jira.<br/><br/>
