# Site settings
title: Gian Rothfuchs
twitter_username: none
name: Gian Marco Rothfuchs

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/GianRothfuchs
 - title: LinkedIn
   url: "www.linkedin.com/in/gianrothfuchs"
 - title: StackOverflow
   url: https://stackexchange.com/users/18643492/giro

#List of interesting Github repo/projects to include - optional
github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
 - GianRothfuchs/rlSandbox

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - Matlab
 - VBA
 - HTTP
 - REST
 - SQL
 - Finance
 - Statistics
 - Machine Learning
 - Deep Learning
 - Reinforcement Learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Technical Project Support
   start: Dec 2018
   end: Ongoing
   employer: Swiss Rock Asset Management
   description: Portfolio management system implementation
 - title: Quantitative Analyst
   start: Jun 2015
   end: Nov 2018
   employer: Credit Suisse AG
   description: Quantitative model developer in IRRBB Modelling
 - title: Research Assistant
   start: Jun 2014
   end: Jun 2015
   employer: Swiss National Bank
   description: Internship at International Trade and Capital Flows unit

#Education is required
education:
 - level: "M.A. in Economics"
   date: 2014
   subject: "Econometrics, Economic History, and Finance"
   school: University of Zurich
 - level: "B.A. in Economics"
   date: 2012
   subject: "Econometrics, Economic History, and Finance"
   school: University of Zurich

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/c2c9d6db2b95a351b6fe8e7f25477f26
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/specializations/deep-learning
      optionalimage: http://coursera-university-assets.s3.amazonaws.com/2b/054650300011e9adc895106b89a651/GreyLogoName360x360.png
      date: December 2017
    - title: Blockchain Specialization
      link: https://www.coursera.org/learn/blockchain-basics
      optionalimage: https://s3.amazonaws.com/coursera-course-photos/a8/d79e8065b111e895dda313fb57c8e8/Course1_white.jpg
      date: Ongoing

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018





#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackexchange.com/users/18643492/giro
   flairimageurl: https://www.gravatar.com/avatar/c8b6cca1f5aba57b7f1160459a135467?s=128&d=identicon&r=PG&f=1

intro: |
  This Portfolio contains some of my data science projects.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Jira. I have experience with an array of testing tools and technologies.<br/><br/>